import {
  createTask,
  deleteTask,
  listTasks,
  listTasksToday,
  listTasksRecurring,
  updateTaskStatus,
  softDeleteTask,
  moveToTrash,
  toggleTaskStatus,
  restoreTask,
  editTask,
  toggleSubtask,
  deleteSubtask,
  syncRecurringTasksForUser,
  completeTaskWithSubtasks,
  uncompleteSubtask,
} from './actions'

export const tasksAPI = {
  create: createTask,
  list: (page = 1, listId?: number) => listTasks(page, undefined, listId),
  listToday: listTasksToday,
  listRecurring: listTasksRecurring,
  updateStatus: updateTaskStatus,
  delete: deleteTask,
  softDelete: softDeleteTask,
  trash: moveToTrash,
  toggleStatus: toggleTaskStatus,
  restore: restoreTask,
  edit: editTask,
  toggleSubtask,
  deleteSubtask,
  syncTasks: syncRecurringTasksForUser,
  completeWithSubtasks: completeTaskWithSubtasks,
  uncompleteSubtask,
}
