import {
  getTeamsAccess,
  listTeams,
  createTeam,
  renameTeam,
  deleteTeam,
  getTeamOverview,
  listTeamRoles,
  createTeamRole,
  updateTeamRole,
  deleteTeamRole,
  addTeamMember,
  updateTeamMemberRole,
  removeTeamMember,
} from './actions'

export const teamsAPI = {
  getAccess: getTeamsAccess,
  list: listTeams,
  create: createTeam,
  rename: renameTeam,
  delete: deleteTeam,
  getOverview: getTeamOverview,
  listRoles: listTeamRoles,
  createRole: createTeamRole,
  updateRole: updateTeamRole,
  deleteRole: deleteTeamRole,
  addMember: addTeamMember,
  updateMemberRole: updateTeamMemberRole,
  removeMember: removeTeamMember,
}
