/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    media: Media;
    tasks: Task;
    'task-completions': TaskCompletion;
    'user-tags': UserTag;
    lists: List;
    'timer-categories': TimerCategory;
    'timer-sessions': TimerSession;
    'timer-configs': TimerConfig;
    'calendar-events': CalendarEvent;
    'calendar-categories': CalendarCategory;
    'google-calendar-syncs': GoogleCalendarSync;
    habits: Habit;
    'habit-completions': HabitCompletion;
    connections: Connection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    'task-completions': TaskCompletionsSelect<false> | TaskCompletionsSelect<true>;
    'user-tags': UserTagsSelect<false> | UserTagsSelect<true>;
    lists: ListsSelect<false> | ListsSelect<true>;
    'timer-categories': TimerCategoriesSelect<false> | TimerCategoriesSelect<true>;
    'timer-sessions': TimerSessionsSelect<false> | TimerSessionsSelect<true>;
    'timer-configs': TimerConfigsSelect<false> | TimerConfigsSelect<true>;
    'calendar-events': CalendarEventsSelect<false> | CalendarEventsSelect<true>;
    'calendar-categories': CalendarCategoriesSelect<false> | CalendarCategoriesSelect<true>;
    'google-calendar-syncs': GoogleCalendarSyncsSelect<false> | GoogleCalendarSyncsSelect<true>;
    habits: HabitsSelect<false> | HabitsSelect<true>;
    'habit-completions': HabitCompletionsSelect<false> | HabitCompletionsSelect<true>;
    connections: ConnectionsSelect<false> | ConnectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  title: string;
  description?: string | null;
  status: 'active' | 'completed' | 'deleted' | 'inactive';
  userId: string;
  list?: (number | null) | List;
  type: 'simple' | 'recurring';
  tags?: ('urgent' | 'work' | 'personal' | 'health' | 'finance' | 'learning')[] | null;
  customTags?: (number | UserTag)[] | null;
  subtasks?:
    | {
        title: string;
        done?: boolean | null;
        description?: string | null;
        dueDate?: string | null;
        tags?: ('urgent' | 'work' | 'personal' | 'health' | 'finance' | 'learning')[] | null;
        id?: string | null;
      }[]
    | null;
  recurrence?: {
    frequency?: ('daily' | 'custom') | null;
    days?: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[] | null;
  };
  dueDate?: string | null;
  /**
   * Date when the task was marked as completed. Used for analytics.
   */
  completedAt?: string | null;
  /**
   * Estimated duration in minutes. Used for calendar display.
   */
  estimatedDuration?: number | null;
  /**
   * Automatically move to trash when the due date is passed.
   */
  autoDeleteOnDueDate?: boolean | null;
  /**
   * Date when the task was soft deleted.
   */
  trashedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lists".
 */
export interface List {
  id: number;
  name: string;
  /**
   * Auto-generated from name
   */
  slug?: string | null;
  userId: string;
  category?: {
    name?: string | null;
    color?: string | null;
  };
  /**
   * La liste Todo par défaut créée automatiquement à l'inscription
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-tags".
 */
export interface UserTag {
  id: number;
  name: string;
  color: string;
  userId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-completions".
 */
export interface TaskCompletion {
  id: number;
  userId: string;
  taskId: number;
  taskTitle: string;
  completedAt: string;
  tags?: ('urgent' | 'work' | 'personal' | 'health' | 'finance' | 'learning')[] | null;
  /**
   * Snapshot of custom tags at completion time: [{ id, name, color }]
   */
  customTagsSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  listId?: number | null;
  listName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timer-categories".
 */
export interface TimerCategory {
  id: number;
  name: string;
  color: string;
  userId: string;
  /**
   * Default categories provided by the app
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timer-sessions".
 */
export interface TimerSession {
  id: number;
  userId: string;
  startedAt: string;
  /**
   * Duration in seconds
   */
  duration: number;
  categoryName?: string | null;
  categoryColor?: string | null;
  subCategory?: string | null;
  subCategoryColor?: string | null;
  taskId?: number | null;
  taskTitle?: string | null;
  /**
   * Session rating from 0 to 5 (0.5 increments)
   */
  rating?: number | null;
  taskCompleted?: boolean | null;
  timezoneOffset?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timer-configs".
 */
export interface TimerConfig {
  id: number;
  userId: string;
  /**
   * Auto-generated or user-defined label
   */
  name: string;
  /**
   * Seconds — 0 means free mode
   */
  sessionDuration?: number | null;
  workDuration?: number | null;
  breakDuration?: number | null;
  categoryName?: string | null;
  categoryColor?: string | null;
  subCategory?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-events".
 */
export interface CalendarEvent {
  id: number;
  userId: string;
  title: string;
  description?: string | null;
  startDate: string;
  endDate: string;
  allDay?: boolean | null;
  color?: string | null;
  /**
   * Reference to calendar-categories id
   */
  categoryId?: number | null;
  recurrence?: {
    frequency?: ('daily' | 'weekly' | 'monthly' | 'yearly') | null;
    interval?: number | null;
    daysOfWeek?: ('0' | '1' | '2' | '3' | '4' | '5' | '6')[] | null;
    monthlyType?: ('dayOfMonth' | 'dayOfWeek') | null;
    endType?: ('never' | 'onDate' | 'afterCount') | null;
    endDate?: string | null;
    endCount?: number | null;
  };
  /**
   * Dates excluded from the recurrence
   */
  exceptions?:
    | {
        date: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Series adjustments from a given date (thisAndFollowing)
   */
  adjustments?:
    | {
        /**
         * From this occurrence date onwards
         */
        fromDate: string;
        /**
         * New start time for occurrences from fromDate
         */
        startDate?: string | null;
        /**
         * New end time for occurrences from fromDate
         */
        endDate?: string | null;
        title?: string | null;
        description?: string | null;
        color?: string | null;
        categoryId?: number | null;
        allDay?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ID of the parent recurring event (modified occurrence)
   */
  recurrenceId?: number | null;
  /**
   * The original occurrence date this event overrides
   */
  originalDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-categories".
 */
export interface CalendarCategory {
  id: number;
  userId: string;
  name: string;
  color: string;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-calendar-syncs".
 */
export interface GoogleCalendarSync {
  id: number;
  userId: string;
  nextSyncToken?: string | null;
  lastSyncedAt?: string | null;
  calendars?:
    | {
        googleId: string;
        name: string;
        color?: string | null;
        primary?: boolean | null;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  status?: ('connected' | 'disconnected' | 'error') | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "habits".
 */
export interface Habit {
  id: number;
  userId: string;
  name: string;
  /**
   * Auto-generated from name + userId
   */
  slug?: string | null;
  description?: string | null;
  color?: string | null;
  categoryTag?: string | null;
  frequency: 'daily' | 'days_of_week' | 'every_x_days' | 'times_per_week';
  daysOfWeek?: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[] | null;
  repeatEveryDays?: number | null;
  timesPerWeek?: number | null;
  /**
   * Optional start date for the habit
   */
  startDate?: string | null;
  archivedAt?: string | null;
  order?: number | null;
  showInCalendar?: boolean | null;
  calendarMode?: ('time' | 'relative') | null;
  /**
   * HH:mm format
   */
  habitTime?: string | null;
  /**
   * Duration in minutes
   */
  habitDuration?: number | null;
  relativePosition?: ('before' | 'after') | null;
  relativeEventId?: number | null;
  /**
   * Array of TrackingField objects
   */
  trackingFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Legacy single HabitGoal — migré vers goals[]
   */
  goal?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  goalCompletedAt?: string | null;
  /**
   * Array of HabitGoal objects
   */
  goals?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  archivedLongestStreak?: number | null;
  archivedTotalCompletions?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "habit-completions".
 */
export interface HabitCompletion {
  id: number;
  userId: string;
  habitId: number;
  completedAt: string;
  note?: string | null;
  /**
   * Record<fieldKey, number | string | boolean>
   */
  trackingValues?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections".
 */
export interface Connection {
  id: number;
  /**
   * userId of the person who sent the connection request
   */
  requesterId: string;
  /**
   * userId of the person who received the connection request
   */
  recipientId: string;
  status: 'pending' | 'accepted';
  /**
   * Set when the request is accepted
   */
  respondedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'task-completions';
        value: number | TaskCompletion;
      } | null)
    | ({
        relationTo: 'user-tags';
        value: number | UserTag;
      } | null)
    | ({
        relationTo: 'lists';
        value: number | List;
      } | null)
    | ({
        relationTo: 'timer-categories';
        value: number | TimerCategory;
      } | null)
    | ({
        relationTo: 'timer-sessions';
        value: number | TimerSession;
      } | null)
    | ({
        relationTo: 'timer-configs';
        value: number | TimerConfig;
      } | null)
    | ({
        relationTo: 'calendar-events';
        value: number | CalendarEvent;
      } | null)
    | ({
        relationTo: 'calendar-categories';
        value: number | CalendarCategory;
      } | null)
    | ({
        relationTo: 'google-calendar-syncs';
        value: number | GoogleCalendarSync;
      } | null)
    | ({
        relationTo: 'habits';
        value: number | Habit;
      } | null)
    | ({
        relationTo: 'habit-completions';
        value: number | HabitCompletion;
      } | null)
    | ({
        relationTo: 'connections';
        value: number | Connection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  status?: T;
  userId?: T;
  list?: T;
  type?: T;
  tags?: T;
  customTags?: T;
  subtasks?:
    | T
    | {
        title?: T;
        done?: T;
        description?: T;
        dueDate?: T;
        tags?: T;
        id?: T;
      };
  recurrence?:
    | T
    | {
        frequency?: T;
        days?: T;
      };
  dueDate?: T;
  completedAt?: T;
  estimatedDuration?: T;
  autoDeleteOnDueDate?: T;
  trashedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-completions_select".
 */
export interface TaskCompletionsSelect<T extends boolean = true> {
  userId?: T;
  taskId?: T;
  taskTitle?: T;
  completedAt?: T;
  tags?: T;
  customTagsSnapshot?: T;
  listId?: T;
  listName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-tags_select".
 */
export interface UserTagsSelect<T extends boolean = true> {
  name?: T;
  color?: T;
  userId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lists_select".
 */
export interface ListsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  userId?: T;
  category?:
    | T
    | {
        name?: T;
        color?: T;
      };
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timer-categories_select".
 */
export interface TimerCategoriesSelect<T extends boolean = true> {
  name?: T;
  color?: T;
  userId?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timer-sessions_select".
 */
export interface TimerSessionsSelect<T extends boolean = true> {
  userId?: T;
  startedAt?: T;
  duration?: T;
  categoryName?: T;
  categoryColor?: T;
  subCategory?: T;
  subCategoryColor?: T;
  taskId?: T;
  taskTitle?: T;
  rating?: T;
  taskCompleted?: T;
  timezoneOffset?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timer-configs_select".
 */
export interface TimerConfigsSelect<T extends boolean = true> {
  userId?: T;
  name?: T;
  sessionDuration?: T;
  workDuration?: T;
  breakDuration?: T;
  categoryName?: T;
  categoryColor?: T;
  subCategory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-events_select".
 */
export interface CalendarEventsSelect<T extends boolean = true> {
  userId?: T;
  title?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  allDay?: T;
  color?: T;
  categoryId?: T;
  recurrence?:
    | T
    | {
        frequency?: T;
        interval?: T;
        daysOfWeek?: T;
        monthlyType?: T;
        endType?: T;
        endDate?: T;
        endCount?: T;
      };
  exceptions?:
    | T
    | {
        date?: T;
        id?: T;
      };
  adjustments?:
    | T
    | {
        fromDate?: T;
        startDate?: T;
        endDate?: T;
        title?: T;
        description?: T;
        color?: T;
        categoryId?: T;
        allDay?: T;
        id?: T;
      };
  recurrenceId?: T;
  originalDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-categories_select".
 */
export interface CalendarCategoriesSelect<T extends boolean = true> {
  userId?: T;
  name?: T;
  color?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-calendar-syncs_select".
 */
export interface GoogleCalendarSyncsSelect<T extends boolean = true> {
  userId?: T;
  nextSyncToken?: T;
  lastSyncedAt?: T;
  calendars?:
    | T
    | {
        googleId?: T;
        name?: T;
        color?: T;
        primary?: T;
        enabled?: T;
        id?: T;
      };
  status?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "habits_select".
 */
export interface HabitsSelect<T extends boolean = true> {
  userId?: T;
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  categoryTag?: T;
  frequency?: T;
  daysOfWeek?: T;
  repeatEveryDays?: T;
  timesPerWeek?: T;
  startDate?: T;
  archivedAt?: T;
  order?: T;
  showInCalendar?: T;
  calendarMode?: T;
  habitTime?: T;
  habitDuration?: T;
  relativePosition?: T;
  relativeEventId?: T;
  trackingFields?: T;
  goal?: T;
  goalCompletedAt?: T;
  goals?: T;
  archivedLongestStreak?: T;
  archivedTotalCompletions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "habit-completions_select".
 */
export interface HabitCompletionsSelect<T extends boolean = true> {
  userId?: T;
  habitId?: T;
  completedAt?: T;
  note?: T;
  trackingValues?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections_select".
 */
export interface ConnectionsSelect<T extends boolean = true> {
  requesterId?: T;
  recipientId?: T;
  status?: T;
  respondedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}